# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: sainsmart_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - rotate_base
    - arm_shaft_joint_a
    - arm_shaft_joint_b
    - cross_shaft_rotation
    - wrist_rotation
    - interface_rotation
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - rotate_base
    - arm_shaft_joint_a
    - arm_shaft_joint_b
    - cross_shaft_rotation
    - wrist_rotation
    - interface_rotation
  gains:
    rotate_base:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_shaft_joint_a:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_shaft_joint_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    cross_shaft_rotation:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_rotation:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    interface_rotation:
      p: 100
      d: 1
      i: 1
      i_clamp: 1